name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:buster
    steps:
      - name: Install git and devscripts
        run: |
          apt-get update
          apt-get install -y git devscripts

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          apt-get update
          apt-get build-dep -y .

      - name: Build deb package
        run: |
          debuild -us -uc

      - name: Upload deb package artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: ../*.deb

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download deb package artifact
        uses: actions/download-artifact@v4
        with:
          name: deb-package
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
