name: Build and Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g. 1.0.0)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
    steps:
      - name: Install git and devscripts
        run: |
          apt-get update
          apt-get install -y git devscripts

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          apt-get update
          apt-get build-dep -y .

      - name: Build deb package
        run: |
          debuild -us -uc
          mkdir -p ./deb_packages
          mv ../*.deb ./deb_packages/
          ls -l ./deb_packages/

      - name: Upload deb package artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: ./deb_packages/*.deb

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download deb package artifact
        uses: actions/download-artifact@v4
        with:
          name: deb-package
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.release_version }}
          name: Release ${{ github.event.inputs.release_version }}
          files: ./artifacts/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}